### ISSUE TITLE
What is the relationship between qtmypaint and QTLibmypaint

### ISSUE THREAD

**Issue by hankcs** [feeef/QTMyPaint#6]
Hello feeel, your project is amazing!

But I found a so-called QTLibmypaint : https://github.com/zhangxiang2014/QTLibmypaint , with amost the same code but no licence attached.

I don't know which one is original, and I guess that one is just a fake version copying from this one.

**Comment by feeef** [comment]
It looks like the other version forked this one at the very beginning. It happened just before I added the licence to the source files (something I forgot to do) so it is why there is no licence in the other one. The lib was not doing much at the time and the code of the core library has improved a lot since then. 

Anyway, if you want to integrate libmypaint within your qt app, I would suggest you go with my version because if the other one has no licence, it is not free software. This one is licenced under GPL v3 and all the files display the licence now! :)

**Comment by hankcs** [comment]
I got it. Thank you!
